<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.h.XtETc' shared service.

return $this->privates['.service_locator.h.XtETc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'command' => array('privates', 'App\\Repository\\CommandRepository', 'getCommandRepositoryService.php', true),
    'eventrepo' => array('privates', 'App\\Repository\\EventRepository', 'getEventRepositoryService.php', true),
    'mailer' => array('services', 'swiftmailer.mailer.default', 'getSwiftmailer_Mailer_DefaultService.php', true),
    'manager' => array('services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService.php', true),
    'repo' => array('privates', 'App\\Repository\\EventRepository', 'getEventRepositoryService.php', true),
    'user' => array('privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService.php', true),
));
