<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.JOQIDtv' shared service.

return $this->privates['.service_locator.JOQIDtv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'event' => array('privates', 'App\\Repository\\EventRepository', 'getEventRepositoryService.php', true),
));
