<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.SYmDgbI' shared service.

return $this->privates['.service_locator.SYmDgbI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'encoder' => array('services', 'security.password_encoder', 'getSecurity_PasswordEncoderService.php', true),
    'mailer' => array('services', 'swiftmailer.mailer.default', 'getSwiftmailer_Mailer_DefaultService.php', true),
    'manager' => array('services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService.php', true),
));
