<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/TraceableValueResolver.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'App\\Controller\\CategoryController::delete' => array('privates', '.service_locator..JzDQIR', 'get_ServiceLocator__JzDQIRService.php', true),
    'App\\Controller\\CategoryController::edit' => array('privates', '.service_locator..JzDQIR', 'get_ServiceLocator__JzDQIRService.php', true),
    'App\\Controller\\CategoryController::index' => array('privates', '.service_locator.a.laFVK', 'get_ServiceLocator_A_LaFVKService.php', true),
    'App\\Controller\\CategoryController::show' => array('privates', '.service_locator..JzDQIR', 'get_ServiceLocator__JzDQIRService.php', true),
    'App\\Controller\\EventController::ShowEvent' => array('privates', '.service_locator.h.XtETc', 'get_ServiceLocator_H_XtETcService.php', true),
    'App\\Controller\\EventController::command' => array('privates', '.service_locator.E_WfFxY', 'get_ServiceLocator_EWfFxYService.php', true),
    'App\\Controller\\EventController::new' => array('privates', '.service_locator.JOQIDtv', 'get_ServiceLocator_JOQIDtvService.php', true),
    'App\\Controller\\SecurityController::activation' => array('privates', '.service_locator.3wcTBi_', 'get_ServiceLocator_3wcTBiService.php', true),
    'App\\Controller\\SecurityController::login' => array('privates', '.service_locator.czKK4py', 'get_ServiceLocator_CzKK4pyService.php', true),
    'App\\Controller\\SecurityController::logout' => array('privates', '.service_locator.czKK4py', 'get_ServiceLocator_CzKK4pyService.php', true),
    'App\\Controller\\SecurityController::registration' => array('privates', '.service_locator.SYmDgbI', 'get_ServiceLocator_SYmDgbIService.php', true),
    'App\\Controller\\CategoryController:delete' => array('privates', '.service_locator..JzDQIR', 'get_ServiceLocator__JzDQIRService.php', true),
    'App\\Controller\\CategoryController:edit' => array('privates', '.service_locator..JzDQIR', 'get_ServiceLocator__JzDQIRService.php', true),
    'App\\Controller\\CategoryController:index' => array('privates', '.service_locator.a.laFVK', 'get_ServiceLocator_A_LaFVKService.php', true),
    'App\\Controller\\CategoryController:show' => array('privates', '.service_locator..JzDQIR', 'get_ServiceLocator__JzDQIRService.php', true),
    'App\\Controller\\EventController:ShowEvent' => array('privates', '.service_locator.h.XtETc', 'get_ServiceLocator_H_XtETcService.php', true),
    'App\\Controller\\EventController:command' => array('privates', '.service_locator.E_WfFxY', 'get_ServiceLocator_EWfFxYService.php', true),
    'App\\Controller\\EventController:new' => array('privates', '.service_locator.JOQIDtv', 'get_ServiceLocator_JOQIDtvService.php', true),
    'App\\Controller\\SecurityController:activation' => array('privates', '.service_locator.3wcTBi_', 'get_ServiceLocator_3wcTBiService.php', true),
    'App\\Controller\\SecurityController:login' => array('privates', '.service_locator.czKK4py', 'get_ServiceLocator_CzKK4pyService.php', true),
    'App\\Controller\\SecurityController:logout' => array('privates', '.service_locator.czKK4py', 'get_ServiceLocator_CzKK4pyService.php', true),
    'App\\Controller\\SecurityController:registration' => array('privates', '.service_locator.SYmDgbI', 'get_ServiceLocator_SYmDgbIService.php', true),
))), ($this->privates['debug.stopwatch'] ?? ($this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))));
