<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRa3onmJ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRa3onmJ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRa3onmJ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRa3onmJ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerRa3onmJ\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'Ra3onmJ',
    'container.build_id' => '59c85811',
    'container.build_time' => 1603432727,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerRa3onmJ');
